FROM cirrusci/flutter:stable

ENV ANDROID_PLATFORM_VERSION_29 29
ENV ANDROID_BUILD_TOOLS_VERSION_29 29.0.3

RUN yes | sdkmanager \
    "platforms;android-$ANDROID_PLATFORM_VERSION_29" \
    "build-tools;$ANDROID_BUILD_TOOLS_VERSION_29"

ENV ANDROID_PLATFORM_VERSION_28 28
ENV ANDROID_BUILD_TOOLS_VERSION_28 28.0.3

RUN yes | sdkmanager \
    "platforms;android-$ANDROID_PLATFORM_VERSION_28" \
    "build-tools;$ANDROID_BUILD_TOOLS_VERSION_28"
